config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :peers
  resources :endpoints
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endpoint.rb
class Endpoint < ApplicationRecord
  has_many :peer
  validates :name, presence: true
end

app/models/peer.rb
class Peer < ApplicationRecord
  has_one :endpoint
  validates :name, presence: true
  validates :public_key, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def root
    puts "hello, world!"
  end
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /endpoints
  # GET /endpoints.json
  def index
    @endpoints = Endpoint.all
  end

  # GET /endpoints/1
  # GET /endpoints/1.json
  def show
  end

  # GET /endpoints/new
  def new
    @endpoint = Endpoint.new
  end

  # GET /endpoints/1/edit
  def edit
  end

  # POST /endpoints
  # POST /endpoints.json
  def create
    @endpoint = Endpoint.new(endpoint_params)

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully created.' }
        format.json { render :show, status: :created, location: @endpoint }
      else
        format.html { render :new }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endpoints/1
  # PATCH/PUT /endpoints/1.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @endpoint }
      else
        format.html { render :edit }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.json
  def destroy
    @endpoint.destroy
    respond_to do |format|
      format.html { redirect_to endpoints_url, notice: 'Endpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endpoint
      @endpoint = Endpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endpoint_params
      params.require(:endpoint).permit(:name, :description)
    end
end

app/controllers/peers_controller.rb
class PeersController < ApplicationController
  before_action :set_peer, only: [:show, :edit, :update, :destroy]

  # GET /peers
  # GET /peers.json
  def index
    @peers = Peer.all
  end

  # GET /peers/1
  # GET /peers/1.json
  def show
  end

  # GET /peers/new
  def new
    @peer = Peer.new
  end

  # GET /peers/1/edit
  def edit
  end

  # POST /peers
  # POST /peers.json
  def create
    @peer = Peer.new(peer_params)

    respond_to do |format|
      if @peer.save
        format.html { redirect_to @peer, notice: 'Peer was successfully created.' }
        format.json { render :show, status: :created, location: @peer }
      else
        format.html { render :new }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peers/1
  # PATCH/PUT /peers/1.json
  def update
    respond_to do |format|
      if @peer.update(peer_params)
        format.html { redirect_to @peer, notice: 'Peer was successfully updated.' }
        format.json { render :show, status: :ok, location: @peer }
      else
        format.html { render :edit }
        format.json { render json: @peer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peers/1
  # DELETE /peers/1.json
  def destroy
    @peer.destroy
    respond_to do |format|
      format.html { redirect_to peers_url, notice: 'Peer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peer
      @peer = Peer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peer_params
      params.require(:peer).permit(:name, :public_key, :is_connected, :endpoint_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
end

app/helpers/peers_helper.rb
module PeersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/endpoints/_form.html.erb
<%= form_with(model: endpoint, local: true) do |form| %>
  <% if endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% endpoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= endpoint.name %></td>
        <td><%= endpoint.description %></td>
        <td><%= link_to 'Show', endpoint %></td>
        <td><%= link_to 'Edit', edit_endpoint_path(endpoint) %></td>
        <td><%= link_to 'Destroy', endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endpoint', new_endpoint_path %>

app/views/endpoints/new.html.erb
<h1>New Endpoint</h1>

<%= render 'form', endpoint: @endpoint %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @endpoint.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @endpoint.description %>
</p>

<%= link_to 'Edit', edit_endpoint_path(@endpoint) %> |
<%= link_to 'Back', endpoints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WgWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peers/_form.html.erb
<%= form_with(model: peer, local: true) do |form| %>
  <% if peer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peer.errors.count, "error") %> prohibited this peer from being saved:</h2>

      <ul>
      <% peer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :public_key %>
    <%= form.text_field :public_key %>
  </div>

  <div class="field">
    <%= form.label :is_connected %>
    <%= form.check_box :is_connected %>
  </div>

  <div class="field">
    <%= form.label :endpoint_id %>
    <%= form.number_field :endpoint_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peers/edit.html.erb
<h1>Editing Peer</h1>

<%= render 'form', peer: @peer %>

<%= link_to 'Show', @peer %> |
<%= link_to 'Back', peers_path %>

app/views/peers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public key</th>
      <th>Is connected</th>
      <th>Endpoint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peers.each do |peer| %>
      <tr>
        <td><%= peer.name %></td>
        <td><%= peer.public_key %></td>
        <td><%= peer.is_connected %></td>
        <td><%= peer.endpoint_id %></td>
        <td><%= link_to 'Show', peer %></td>
        <td><%= link_to 'Edit', edit_peer_path(peer) %></td>
        <td><%= link_to 'Destroy', peer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peer', new_peer_path %>

app/views/peers/new.html.erb
<h1>New Peer</h1>

<%= render 'form', peer: @peer %>

<%= link_to 'Back', peers_path %>

app/views/peers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peer.name %>
</p>

<p>
  <strong>Public key:</strong>
  <%= @peer.public_key %>
</p>

<p>
  <strong>Is connected:</strong>
  <%= @peer.is_connected %>
</p>

<p>
  <strong>Endpoint:</strong>
  <%= @peer.endpoint_id %>
</p>

<%= link_to 'Edit', edit_peer_path(@peer) %> |
<%= link_to 'Back', peers_path %>

app/views/welcome/index.html.erb
<h1>Hello, world!</h1>